name: ci

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        attr: [grpc-haskell-core grpc-haskell grpc]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            system-features = nixos-test benchmark big-parallel kvm

      - name: Nix build for “${{ matrix.attr }}” on ${{ matrix.os }}
        run: nix-build -A ${{ matrix.attr }}
